#!/usr/bin/env bash
# ============================================================
# apparmor.sh - Manage AppArmor profile for msmtp
# ============================================================
# Features:
# - Loads optional .env for configurable paths
# - Supports DRY_RUN=1 to preview actions without applying
# - Uses consistent logging and state recording
# - Records profile source, path, and hash
# ============================================================

source "$(dirname "$0")/utils.sh"

# --- Load .env global if present ---
load_env_file() {
    local env_file=""
    if [[ -f "$(dirname "$0")/.env" ]]; then
        env_file="$(dirname "$0")/.env"
    elif [[ -f ".env" ]]; then
        env_file=".env"
    fi
    if [[ -n "$env_file" ]]; then
        log_info "AppArmor: loading environment variables from $env_file"
        set -a
        source "$env_file"
        set +a
    fi
}

ensure_apparmor_profile() {
    section "Ensuring AppArmor profile for msmtp"

    load_env_file

    local profile_src="/etc/apparmor.d/usr.bin.msmtp"
    local profile_template="/usr/share/apparmor/extra-profiles/usr.bin.msmtp"
    local custom_profile="/opt/msmtp-profile"

    # Allow overriding paths from .env
    profile_src="${APPARMOR_PROFILE_SRC:-$profile_src}"
    profile_template="${APPARMOR_PROFILE_TEMPLATE:-$profile_template}"
    custom_profile="${APPARMOR_CUSTOM_PROFILE:-$custom_profile}"

    # Detect container environment
    if [[ -f /.dockerenv ]] || grep -qa container=lxc /proc/1/environ; then
        log_warn "AppArmor: running inside a container — support may be limited."
        set_state "apparmor_env" "container"
    else
        set_state "apparmor_env" "host"
    fi

    # Check AppArmor support
    if ! command -v apparmor_status >/dev/null 2>&1; then
        log_warn "AppArmor: not supported in this environment (apparmor_status not found)."
        set_state "apparmor" "unsupported"
        return 0
    fi

    # Check AppArmor service
    if ! systemctl is-active --quiet apparmor; then
        log_warn "AppArmor: service is not active."
        set_state "apparmor" "inactive"
        return 0
    fi

    set_state "apparmor" "active"

    # Check if profile already loaded
    if apparmor_status | grep -q "msmtp"; then
        log_info "AppArmor: profile for msmtp is already loaded."
        set_state "apparmor_profile" "loaded"
        set_state "apparmor_profile_path" "$profile_src"
        return 0
    fi

    log_warn "AppArmor: no profile found for msmtp. Attempting to install one."

    # Ensure writable directory
    require_writable_dir "/etc/apparmor.d"

    # Backup existing profile
    [[ -f "$profile_src" ]] && backup_file "$profile_src"

    if [[ "$DRY_RUN" == "1" ]]; then
        log_info "DRY_RUN enabled — would install AppArmor profile from:"
        log_info "  - Custom: $custom_profile"
        log_info "  - Template: $profile_template"
        log_info "  - Or generate minimal profile"
        return 0
    fi

    # Use custom profile if available
    if [[ -f "$custom_profile" ]]; then
        log_info "AppArmor: using custom profile from $custom_profile"
        cp "$custom_profile" "$profile_src"
        set_state "apparmor_profile_src" "custom"
    elif [[ -f "$profile_template" ]]; then
        safe_run "copy msmtp AppArmor profile" cp "$profile_template" "$profile_src"
        set_state "apparmor_profile_src" "template"
    else
        # Generate minimal profile
        cat > "$profile_src" <<'EOF'
# AppArmor profile for msmtp
# Generated by msmtp installer
#include <tunables/global>

 /usr/bin/msmtp {
    #include <abstractions/base>
    #include <abstractions/nameservice>
    #include <abstractions/ssl_certs>

    /etc/msmtprc r,
    /etc/msmtp.secrets/** r,
    /var/log/msmtp/** rw,

    /usr/bin/msmtp mr,

    network inet stream,
    network inet6 stream,

    deny /** w,
}
EOF
        log_info "AppArmor: created a minimal profile for msmtp."
        set_state "apparmor_profile_src" "generated"
    fi

    # Validate syntax
    if ! apparmor_parser -Q "$profile_src"; then
        log_error "AppArmor: profile syntax check failed for $profile_src"
        set_state "apparmor_profile" "invalid"
        cp "$profile_src" /var/log/msmtp/apparmor_failed_profile.txt
        log_warn "AppArmor: saved failed profile to /var/log/msmtp/apparmor_failed_profile.txt"
        return 0
    fi

    # Reload profile
    safe_run "reload AppArmor profiles" apparmor_parser -r "$profile_src"

    # Verify load
    if apparmor_status | grep -q "msmtp"; then
        log_info "AppArmor: profile for msmtp loaded successfully."
        set_state "apparmor_profile" "loaded"
    else
        log_warn "AppArmor: failed to load profile for msmtp."
        set_state "apparmor_profile" "failed"
        cp "$profile_src" /var/log/msmtp/apparmor_failed_profile.txt
        log_warn "AppArmor: saved failed profile to /var/log/msmtp/apparmor_failed_profile.txt"
    fi

    # Record path and hash
    if [[ -f "$profile_src" ]]; then
        local profile_hash
        profile_hash=$(sha256sum "$profile_src" | awk '{print $1}')
        set_state "apparmor_profile_path" "$profile_src"
        set_state "apparmor_profile_hash" "$profile_hash"
    fi
}

# Execute if run directly
if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    ensure_apparmor_profile
fi
